import Nav from '@/components/Nav'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import {dark} from "@clerk/themes"
import { Suspense } from 'react'
import { TooltipProvider } from '@/components/Tooltip'
import { Toaster } from '@/components/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{baseTheme: dark}}>
      <TooltipProvider delayDuration={100}>
        <html lang="en">
          <body className={`${inter.className} dark`}>
            <Nav />
            <main>
              <Suspense fallback={<div>Loading...</div>}>
                {children}
              </Suspense>
            </main>
            <Toaster />
          </body>
        </html>
      </TooltipProvider>
    </ClerkProvider>
  )
}
