import Nav from '@/components/Nav'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Suspense } from 'react'
import { TooltipProvider } from '@/components/Tooltip'
import { Toaster } from '@/components/toaster'
import { clerkTheme } from '@/styles/clerk-theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={clerkTheme}>
      <TooltipProvider delayDuration={100}>
        <html lang="en">
          <body className={`${inter.className} dark`}>
            <Nav />
            <main className='pt-16'>
              <Suspense fallback={<div>Loading...</div>}>
                {children}
              </Suspense>
            </main>
            <Toaster />
            {
              /*<Script
              async
              src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID}`}
              strategy="lazyOnload"
              crossOrigin="anonymous"
            />
            <Script async src='/cmp.js' />*/
            }
          </body>
        </html>
      </TooltipProvider>
    </ClerkProvider>
  )
}
